import Link from "next/link";
import { AnalysisList } from "@/components/ipo/AnalysisList";
import { UploadCard } from "@/components/ipo/UploadCard";

export default function Home() {
  return (
    <main className="mx-auto flex w-full max-w-6xl flex-1 flex-col gap-6 px-4 py-8 sm:px-6">
      <header className="flex flex-col gap-1">
        <h1 className="text-2xl font-semibold tracking-tight">IPO Analyser</h1>
        <p className="max-w-3xl text-muted-foreground">
          Upload an Indian IPO&apos;s offer document. Six AI agents read its risk factors, financials, business,
          offer structure and legal chapters, and a scoring rubric turns their findings into a report where every
          point cites its page.
        </p>
      </header>

      <div className="grid gap-6 lg:grid-cols-[minmax(0,420px)_minmax(0,1fr)]">
        <UploadCard />
        <AnalysisList />
      </div>

      <footer className="mt-auto flex flex-col gap-1 border-t pt-4 text-sm text-muted-foreground">
        <p>
          Educational analysis generated by AI from the offer document only. It may contain errors and is not
          investment advice.
        </p>
        <Link href="/general" className="w-fit hover:text-foreground">
          General document Q&amp;A (the previous version of this app) →
        </Link>
      </footer>
    </main>
  );
}
